import { Pokemon } from './interfaces/pokemon.interface';

export const POKEMONS: Pokemon[] = [
  {
    id: 1,
    number: '001',
    name: 'Bulbasaur',
    types: [
      { id: 1, name: 'Grass' },
      { id: 2, name: 'Water' },
    ],
    person: 'Solitare',
    hp: 90,
    hpMax: 100,
    atack: 90,
    def: 110,
    atackSpec: 115,
    defSpec: 65,
    speed: 40,
    level: 25,
    moves: [
      {
        id: 1,
        name: 'scrath',
        accuracy: 100,
        type: { id: 2, name: 'Normal' },
        effect_chance: null,
        pp: 20,
        priority: 10,
        power: 40,
        learnedLevel: 1,
      },
    ],

    activeMoves: [
      {
        id: 1,
        name: 'scrath',
        accuracy: 100,
        type: { id: 2, name: 'Normal' },
        effect_chance: null,
        pp: 20,
        priority: 10,
        power: 40,
        learnedLevel: 1,
        effect: "Inflicts regular damage. User's critical hit rate is one level higher when using this move."
      },
      {
        id: 1,
        name: 'scrath',
        accuracy: 100,
        type: { id: 2, name: 'Grass' },
        effect_chance: null,
        pp: 20,
        priority: 10,
        power: 40,
        learnedLevel: 1,
      },
      {
        id: 1,
        name: 'scrath',
        accuracy: 100,
        type: { id: 2, name: 'Fire' },
        effect_chance: null,
        pp: 20,
        priority: 10,
        power: 40,
        learnedLevel: 1,
      },
      {
        id: 1,
        name: 'scrath',
        accuracy: 100,
        type: { id: 2, name: 'Ice' },
        effect_chance: null,
        pp: 20,
        priority: 10,
        power: 40,
        learnedLevel: 1,
      },
    ],
  },
  {
    id: 1,
    number: '007',
    name: 'Squirtle',
    types: [{ id: 1, name: 'Water' }],
    person: 'Solitare',
    hp: 90,
    hpMax: 100,
    atack: 90,
    def: 110,
    atackSpec: 115,
    defSpec: 65,
    speed: 40,
    level: 25,
    moves: [
      {
        id: 1,
        name: 'scrath',
        accuracy: 100,
        type: { id: 2, name: 'Normal' },
        effect_chance: null,
        pp: 20,
        priority: 10,
        power: 40,
        learnedLevel: 1,
      },
    ],
    activeMoves: [
      {
        id: 1,
        name: 'scrath',
        accuracy: 100,
        type: { id: 2, name: 'Normal' },
        effect_chance: null,
        pp: 20,
        priority: 10,
        power: 40,
        learnedLevel: 1,
      },
    ],
  },
  {
    id: 1,
    number: '004',
    name: 'Charmander',
    types: [{ id: 1, name: 'Fire' }],
    person: 'Solitare',
    hp: 90,
    hpMax: 100,
    atack: 90,
    def: 110,
    atackSpec: 115,
    defSpec: 65,
    speed: 40,
    level: 25,
    moves: [
      {
        id: 1,
        name: 'scrath',
        accuracy: 100,
        type: { id: 2, name: 'Normal' },
        effect_chance: null,
        pp: 20,
        priority: 10,
        power: 40,
        learnedLevel: 1,
      },
    ],
    activeMoves: [
      {
        id: 1,
        name: 'scrath',
        accuracy: 100,
        type: { id: 2, name: 'Normal' },
        effect_chance: null,
        pp: 20,
        priority: 10,
        power: 40,
        learnedLevel: 1,
      },
    ],
  },
  {
    id: 1,
    number: '016',
    name: 'Pidgey',
    types: [{ id: 1, name: 'Normal' }],
    person: 'Solitare',
    hp: 90,
    hpMax: 100,
    atack: 90,
    def: 110,
    atackSpec: 115,
    defSpec: 65,
    speed: 40,
    level: 25,
    moves: [
      {
        id: 1,
        name: 'scrath',
        accuracy: 100,
        type: { id: 2, name: 'Normal' },
        effect_chance: null,
        pp: 20,
        priority: 10,
        power: 40,
        learnedLevel: 1,
      },
    ],
    activeMoves: [
      {
        id: 1,
        name: 'scrath',
        accuracy: 100,
        type: { id: 2, name: 'Normal' },
        effect_chance: null,
        pp: 20,
        priority: 10,
        power: 40,
        learnedLevel: 1,
      },
    ],
  },
  {
    id: 1,
    number: '025',
    name: 'Pikachu',
    types: [{ id: 1, name: 'Eletric' }],
    person: 'Solitare',
    hp: 90,
    hpMax: 100,
    atack: 90,
    def: 110,
    atackSpec: 115,
    defSpec: 65,
    speed: 40,
    level: 25,
    moves: [
      {
        id: 1,
        name: 'scrath',
        accuracy: 100,
        type: { id: 2, name: 'Normal' },
        effect_chance: null,
        pp: 20,
        priority: 10,
        power: 40,
        learnedLevel: 1,
      },
    ],
    activeMoves: [
      {
        id: 1,
        name: 'scrath',
        accuracy: 100,
        type: { id: 2, name: 'Normal' },
        effect_chance: null,
        pp: 20,
        priority: 10,
        power: 40,
        learnedLevel: 1,
      },
    ],
  },
];
